services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: civic-db
    image: civic-db:latest
    restart: always
    environment:
      POSTGRES_USER: civic_db_admin
      POSTGRES_PASSWORD:
    volumes:
      - civic-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  civic-db:
    name: civic-db
